FROM scratch

COPY bin/lumogon /
# TODO - note to future self, we should establish a process for keeping
#        these certs updated
COPY certs/ca-certificates.crt /etc/ssl/certs/
ENTRYPOINT ["/lumogon"]
